-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Feb 14, 2021 at 10:01 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `e-IONICS`
--

-- --------------------------------------------------------

--
-- Table structure for table `contacts`
--

CREATE TABLE `contacts` (
  `sno` int(11) NOT NULL,
  `name` text NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone` varchar(20) NOT NULL,
  `msg` text NOT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contacts`
--

INSERT INTO `contacts` (`sno`, `name`, `email`, `phone`, `msg`, `date`) VALUES
(1, 'Aman Kumar', 'amansingh32@hotmail.com', '+918789423848', 'Hello, Please contact me.', '2021-02-14 20:52:05');

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `sno` int(11) NOT NULL,
  `slug` varchar(30) NOT NULL,
  `title` text NOT NULL,
  `subheading` text NOT NULL,
  `content` text NOT NULL,
  `img_file` varchar(50) DEFAULT NULL,
  `posted_by` text NOT NULL,
  `date` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`sno`, `slug`, `title`, `subheading`, `content`, `img_file`, `posted_by`, `date`) VALUES
(1, 'post-1', 'NTM88: NTM88 HIGHLY INTEGRATED TIRE PRESSURE SENSOR', 'NXP Semiconductors NTM88 Pressure Sensor is a complete, fully-integrated Tire Pressure Monitoring Sensor', '(TPMS) solution in a single, compact package. The NTM88 TPMS solution integrates an 8-bit microcontroller (MCU), a pressure sensor, an accelerometer, and an RF transmitter. The device features low transmit-power consumption, a large customer memory size, and a choice of either dual- or single-axis accelerometer architecture.The NXP Semiconductors NTM88 Pressure Sensor is available in a compact 4.0mm x 4.0mm HQFN24 package with dimple wettable flanks, enabling visible solder joint inspection. Features 100kPa to 900kPa pressure range optionsField-proven accelerometer architecture offers motion detection and tire localization capabilitiesSingle-axis or dual-axis optionsLow-power wakeup timer, free-running counter, and periodic reset are driven by LFO180nA power consumption typical (stand-by at 3.0V, 25℃)Dedicated state machines for reduced power consumption8-bit MCU/S08 core with SIM, interrupt, and debug/monitor512Bytes RAM / 16k Flash (1k for NXP coefficients, 15k for user applications and NXP firmware libraries)Internal 315MHz to 434MHz RF transmitterInternal 125kHz LF receiverSix multipurpose GPIO pins (including two A/D inputs)4.0mm x 4.0mm x 1.98mm HQFN24 package with dimple wettable flanks', 'NTM88_Pressure_Sensor.jpg', 'admin', '2021-02-15 02:11:36'),
(2, 'post-2', 'ULTRA-HIGH ENERGY STORAGE 6 V SUPERCAPACITORS – PTV SERIES', 'ULTRA-HIGH ENERGY STORAGE 6 V SUPERCAPACITORS – PTV SERIES', 'Eaton – Electronics Division’s PTV supercapacitors provide ultra-high capacitance and high-density power with ultra-low ESR for a host of industrial applications. Comprising two TV family cells with passive voltage management, they reduce cell count and simplify designs. These supercapacitors are an excellent source of backup, pulse, and hybrid power in industrial applications. These supercapacitors support hundreds of thousands of charge and discharge cycles with operating lifetimes of up to 20 years. The cells are maintenance-free with zero thermal runaway risk. Each EDLC cell offers 6.0 V (5.0 V at +85°C) of working voltage with operating temperatures from -40°C to +85°C, meeting the higher voltage and temperature requirements of industrial applications. PTV supercapacitors can be utilized as standalone energy storage systems or combined with secondary batteries to optimize the lifetime, runtime, and cost. Features Ultra-high capacitanceExcellent temperature withstand capability (-40°C to +85°C)Higher working voltage 6 V (5.0 V at +85°C) and high current-handling capacityPassive cell voltage managementUltra-low ESR for high power densityLow profile design for space-saving', 'eaton-ptv-supercapacitor.jpg', 'admin', '2021-02-15 02:11:36'),
(3, 'post-3', 'MELEXIS EXTENDS ITS SUCCESSFUL IC FAMILY WITH A NEW LIN RGB LED CONTROLLER', 'The new member – the MLX81114 – supports the further growth of RGB LED-based automotive ambient lighting, also known as LIN RGB', 'The MLX81114 is a variant of the MLX81113 featuring a memory access protection which enables anti-theft applications, and is exclusively available in SOIC packaging.Other features include on-chip memory, high output current and EMC robustness next to the ISO 26262 functional-safety compliance to support its use in ASIL-A classified systems.With automotive lighting as one of the key features for personalization and differentiation within the driver’s cabin, Melexis responds to this trend with its offering of LIN-compatible RGB(W) drivers to enable sophisticated yet cost-effective ambient lighting for vehicles from entry-level to mid-range and luxury models.', 'MLX81114-Single-LIN-RGB.jpg', 'admin', '2021-02-15 02:11:36'),
(4, 'post-4', 'PS9000 FAMILY OF DESKTOP SPACE SAVING INSTRUMENTS', 'The PS9000 family of laboratory power supplies from Elektro-Automatik offers a reliable and user-friendly solution for every electronics engineer. ', 'The microprocessor-controlled laboratory power supplies of EA-PSI 9000 DT series offer a user-friendly, interactive handling concept, along with an extensive set of standard features, which can facilitate their operation. Configuration of output parameters, supervision features and other settings is smart and comfortable. The implemented supervision features for all output parameters can reduce test equipment and make it almost unnecessary to install external supervision hardware and surface.The clear control panel with two knobs, one pushbutton, two LEDs, and the touch panel with a colour TFT display for all important values and status enables the user to handle the device with a few fingers touches easily.The device offers a set of interfaces (analogue and digital) on its rear panel for integration into semi-automatic and remotely controlled test and automation systems. AC Power Supply Input The device uses an active Power Factor Correction (PFC), enabling worldwide usage of a mains input from 90VAC up to 264VAC. Models with 1,5kWwill derate their output power to 1kW below input voltages 150VAC. Auto-Ranging Power Stage All models are equipped with a flexible auto-ranging output stage which provides a higher output voltage at lower output current, or a higher output current at lower output voltage, always limited with a maximum output power curve. Highlights: AutorangingColor Touchscreen3-paths onboard Interface Technical Specifications: Nominal powers 320W, 640W, 1000W, 1500WNominal voltages 40V, 80V, 200V, 750VCurrents 0-60A Available Features: Color TouchscreenWide input supply voltage range 90…264V with active PFCHigh efficiency, up to 92%Interfaces: USB standard, Ethernet & Analog optionalLabVIew-Vis software40V-Models according to SELV under EN 60950 DC Output DC output voltages between 0…40V and 0…750V, output current between 0…4A and 0…60A and output power ratings between 320…1500W are available. Thus, current, voltage and power could be adjusted continuously between 0…100%, no matter if manually or remotely (analogue or digital). The output terminals are located at the front panel of the device.The PSI 9000 DT power supply features an additional built-in output filter to achieve much lower ripple, i.e. low noise on the DC output voltage.Desktop power supplies from Elektro-Automatik are available to order. We will check the price and delivery dates directly with the supplier.', 'obr2543_p8659ef33f3bd.jpg', 'admin', '2021-02-15 02:11:36'),
(5, 'post-5', 'PICO-TGU4 – PICO-ITX BOARD WITH 11TH GENERATION INTEL® CORE™ I7/I5/I3/CELERON® U-SERIES PROCESSOR SOC', 'Pico-ITX Board with 11th Generation Intel® Core™ i7/i5/i3/Celeron® U-Series Processor SoC', 'Features 11th Gen Intel® Core™ i7/i5/i3/Celeron Processor SoCLPDDR4x on board memory, Max. 32 GB2.5GbE Intel i225 + 1GbE Intel i219HDMI2.0b x 1, 4Kx2K + eDP, up to HBR3 8KM.2 2280 M key(PCIE by4 GEN4/SATA) x 1SATA 6.0 Gb/s x 1Full size mSATA/mPCIe x 1 (Select by BIOS, default: mPCIe)2 x USB 3.2 Gen 2, 2 x USB 3.2 Gen 1, 4 x USB 2.0RS-232/422/485 x 2Line-in/Line-out/MICDIO 8 bit', 'pgal_210208_eungyv.jpg', 'admin', '2021-02-15 02:14:09'),
(6, 'post-6', 'STM32 NUCLEO-64 DEVELOPMENT BOARD WITH STM32G491RE MCU, SUPPORTS ARDUINO AND ST MORPHO CONNECTIVITY', 'The STM32 Nucleo-64 board provides an affordable and flexible way for users to try out new concepts and build prototypes by choosing from the various combinations of performance and power consumption features, provided by the STM32 microcontroller.', 'The ARDUINO® Uno V3 connectivity support and the ST morpho headers allow the easy expansion of the functionality of the STM32 Nucleo open development platform with a wide choice of specialized shields. The STM32 Nucleo-64 board does not require any separate probe as it integrates the ST-LINK debugger/programmer.The STM32 Nucleo-64 board comes with the STM32 comprehensive free software libraries and examples available with the STM32Cube MCU Package.Key Features Common featuresSTM32 microcontroller in LQFP64 package1 user LED shared with ARDUINO®1 user and 1 reset push-buttons32.768 kHz crystal oscillatorBoard connectors:ARDUINO® Uno V3 expansion connectorST morpho extension pin headers for full access to all STM32 I/OsFlexible power-supply options: ST-LINK, USB VBUS, or external sourcesOn-board ST-LINK debugger/programmer with USB re-enumeration capability: mass storage, Virtual COM port and debug portComprehensive free software libraries and examples available with the STM32Cube MCU PackageSupport of a wide choice of Integrated Development Environments (IDEs) including IAR Embedded Workbench®, MDK-ARM, and STM32CubeIDEBoard-specific featuresExternal SMPS to generate Vcore logic supply24 MHz HSEBoard connectors:External SMPS experimentation dedicated connectorMicro-AB or Mini-AB USB connector for the ST-LINKMIPI® debug connectorArm® Mbed Enabled™ compliant', 'NUCLEO-G491RE-board.jpg', 'admin', '2021-02-15 02:14:48'),
(7, 'post-7', 'COMMELL UNVEILED LP-179 & LV-6712 BASED ON INTEL TIGER LAKE UP3 PLATFORM', 'Taiwan Commate Computer Inc .(COMMELL), the worldwide leader of Industrial Single Board Computers, unveiled LP-179 & LV-6712 Mini-ITX based on Intel® 11th Gen. FCBGA1449 “Tiger Lake UP3”.', 'The 11th Gen Intel® Core™ processor is claimed to deliver better performance up to a 23% gain in single-thread performance, and up to a 19% gain in multi-thread performance vs. 8th Gen Intel® Core™ processors, up to 96 graphics execution units, deliver high-performance CPU/GPU compute with integrated AI acceleration, plus capabilities for applications that demand high-speed processing, and low-latency deterministic computing.The COMMELL LP-179 & LV-6712 platform provides excellent CPU, graphics, media performance, flexibility, and enhanced security, is ideally suited to applications requiring multi-tasking capabilities, such as gaming, surveillance, medical, defense, transportation and industrial automation application. The LP-179 & LV-6712 Mini-ITX is designed for the 11th generation Intel® Core™ i7-1185G7E and Celeron® 6305E, The Core™ i7 part has a 1.8GHz base clock with 12MB cache and a 4.4GHz max turbo frequency, The Core™ Celeron part has a 1.8GHz base clock frequency with 4MB cache, both CPUs offer long-life availability.The LP-179 features one DDR4-3200 SO-DIMM slot for up to 32GB of memory. LV-6712 features two DDR4-3200 SO-DIMM slot for up to 64GB of memory.LP-179 Displays one HDMI, one DP ports onboard, optional LVDS interface by ADP-3460 module. Lp-179 offers 2 x USB2.0, 2 x USB3.2 Gen2 and 1 x SATAIII, equipped with one Gigabit Ethernet, and one 2.5Gb Ethernet,(1 x Intel® I219-LM Gigabit PHY LAN and 1 x Intel® I225-LM 2.5 Gigabit LAN), and comes with internal 2 x RS232,1 x HD Audio, 1 x M.2 Key M 2280 for support PCIe Gen4 device such as NVMe, 1 x M.2 Key E 2230 for Wi-Fi & BT module, Standard 12V DC input.LV-6712 Displays LVDS, two HDMI and two DP ports onboard, up to four displays can be controlled simultaneously.LV-6712 offers the features as 4 x USB2.0, 4 x USB3.2 Gen2 and 2 x SATAIII, equipped with one Gigabit Ethernet, and one 2.5Gb Ethernet,(1 x Intel® I219-LM Gigabit PHY LAN and 1 x Intel® I225-LM 2.5 Gigabit LAN), 2 x RS232/422/485 onboard and comes with internal PS/2 port, 4 x RS232,1 x 8bits GPIO, 1 x HD Audio, 1 x SMBus, 1 x M.2 Key M 2280 for support PCIe Gen4 device such as NVMe, 2 x MiniPCIe(slot 2 support mSATA), 1 x PCIe X1 slot, Standard 24-Pin ATX or 4-Pin 9~35V DC input.', 'commell_lp179.jpg', 'admin', '2021-02-15 02:15:59'),
(8, 'post-8', 'ARDUINO PORTENTA VISION SHIELD LORA FOR COMPUTER VISION APPLICATIONS', 'Portenta Vision Shield LoRa is another variant in the edge AI vision board that features LoRa wireless connectivity. It comes with a Himax HM-01B0 low-power camera sensor and an all-directional pair of microphones. ', 'We saw the launch of Arduino Porenta H7 last year, it features programming in high-level languages and AI and at the same time, it performs low-latency operations on its customizable hardware. However, the board supported an inbuilt module dedicated to professional and industrial applications, apart from its popularity amongst the hobbyists.Arduino also launched a Vision Shield add-on for enabling edge computer vision on Arduino Porenta H7 in late 2020. The Vision Shield add-on was a significant enhancement, as it allowed the computer vision and “always-on voice capabilities” supporting the additional hardware needed for on-device computing. Technical Specifications Of Arduino Portenta Vision Shield LoRa Himax HM-01B0 camera module for computer vision applicationsResolution of 320 x 320 active pixel resolution with support for QVGAImage sensor features high sensitivity 3.6μ BrightSense pixel technology2x MP34DT05 microphones capable of detecting acoustic waves868/915MHz ABZ-093 LoRa Module with ARM Cortex-M0+ for connectivityLength: 66 mm and Width: 25 mmWeight 8 gramsPortenta Vision Shield LoRa features a camera sensor that works on the core to perform image recognition algorithms. The device uses the OpenMV framework for the Arduino editor. It supports a long-range 868/915MHz LoRa wireless connectivity for Portenta H7 for interfacing IoT with low power consumption. It also comes with a pair of on-board microphones for directional sound detection. This enables real-time sound capturing and analysis. Also, the JTAG connector functions low-level debugging of the device using an external programmer.Talking more about the OpenMV framework, it provides a free license to the OpenMV IDE. The environment is simple to integrate computer vision functionalities using the MicroPython as a programming medium. One can download the OpenMV for Arduino Editor from the professional tutorials site and browse through the examples that the company has created on the platform itself. The Arduino Portenta Vision Shield LoRa is available at a price of $63 from the Arduino Store. For more information visit the official product page. Images and technical specifications have also been taken from the product page.', 'Arduino-Portenta-Vision-Shield-LoRa.jpg', 'admin', '2021-02-15 02:18:42'),
(9, 'post-9', 'QUICKLOGIC LAUNCHES QOMU – AN OPEN SOURCE SOC DEV KIT THAT FITS IN YOUR USB PORT', 'QuickLogic Corporation, a developer of ultra-low power multi-core voice-enabled SoCs, embedded FPGA IP, and endpoint AI solutions', 'Qomu development kit, a tiny form factor Arm® Cortex®-M4F MCU + eFPGA combination that fits into a USB Type A port. Optimized for the QuickLogic Open Reconfigurable Computing (QORC) initiative, the kit is supported by a wide variety of vendor-supported open source development tools, including Zephyr, FreeRTOS, SymbiFlow and Renode, which broadens access and enables designers to develop applications virtually anywhere. Highlights:Tiny form factor fits in USB Type A port found on almost every computer, enabling portability and development anywhereSupported by 100% open source hardware and software tools for the MCU and embedded FPGA coreThe Qomu development kit contains QuickLogic’s EOS S3 MCU + eFPGA SoC, which enables an incredible amount of processing capability for such a tiny development kit. The MCU enables seamless software development while the embedded FPGA (eFPGA) can be used to accelerate or offload algorithms from the MCU, or to simply implement custom IP or provide glue logic. While the kit can implement a wide range of functionality for a broad set of market segments, it is especially well-suited to edge IoT applications – especially those requiring ultra-low power consumption and artificial intelligence or machine learning capabilities. QuickLogic’s QORC initiative has led to a completely open source, vendor supported development tool environment for the Qomu development kit. Open source development tools include SymbiFlow synthesis, place & route, and bitstream generation. Many example applications and gateware are readily available for free. In addition to standard Verilog support with SymbiFlow, Qomu supports nMigen for a Python-to-FPGA design flow.  Additional open source tools include Zephyr, FreeRTOS and Renode.', 'QuickLogic.jpg', 'admin', '2021-02-15 02:19:51'),
(10, 'post-10', 'FIREFLY DUAL-LENS AI CAMERA MODULE SUPPORTS COMPUTER VISION AT EDGE', 'Firefly has launched two dual-lens AI camera modules with a built-in NPU (Neural Processing Unit) accelerator supporting up to 2 TOPS of performance.', 'The modules feature Rockchip’s AI vision processors, RV1109 for CAM-C1109S2U module and RV1126 for CAM-C1126S2U module. The processor also supports FastBoot, TrustZone technology, and multiple crypto engines.CAM-C1109S2U module’s RV1109 SoC comes with a 1.5GHz dual-core Arm Cortex-A7 CPU and a 400MHz RISC-V processor. It is also equipped with a 2D-capable graphics processor, and a VPU (Vision Processing Unit) compatible with H.264/H.265 encoding at 30 fps, and an NPU performing up to 1.2 TOPS.CAM-C1126S2U module comes with a more powerful Rockchip RV1126 which has a quad-core Arm Cortex-A7 instead of the dual-core Arm Cortex-A7 in the CAM-C1109S2U module. Hence, this enhances the capacity of VPU encoding and decoding to allow up to 4K from the visible-light camera module and increases the NPU performance up to 2 TOPS.Both the firefly camera modules have almost similar specifications, apart from the processors. Technical Specifications Of Firefly Camera Modules 1 or 2GB DDR4 RAM constitutes the system memoryStorage of 8 or 16 GB eMMC 4.51 flashRGB camera features 1920×1080 resolution GC2093 image sensor with 650nm filter and 80cm focus distanceIR camera features 1920×1080 resolution GC2053 image sensor with 850nm filter and 80cm focus distance30-pin FPC header to connect MIPI display (TBC) for video outputWorking temperature ranges from 10 to 60°CPower Supply of 5V through USB Type-C port84 x 22.45 x 19.35 mm dimensions with aluminum alloy housing.The on-board video CODEC of the firefly camera modules supports 2K H.254/H.265 at 30FPS and multi-channel video encoding and decoding. Hence, it fulfills the requirement of low bit rate and low-latency encoding. Thus, making the video tenure smaller. The built-in 3F-HDR ISP and 3F-HDR feature multi-level noise reductions. It also comes with a dual-lens 2M (RGB+IR) WDR camera for working in strong light, backlight, and darkness. The Firefly camera modules are compatible with the Linux environment. It operates with the Rockchip RKNN toolkit working in Windows and Mac OS. The AI camera module has dynamic connectivity for host mediums on android devices. The modules run on tools for AI algorithms for direct conversion and deployment of TensorFlow, PyTorch, Caffe, MxNet, DarkNet, ONNX frameworks. Hence, the firefly camera modules are suitable for various ML/DL applications. This includes face recognition and gesture recognition. It can also be used in domains like gate access control, smart security, smart IP camera, smart doorbell/peephole, self-service terminals, smart finance, smart construction, smart travel, and other industries.', 'Firefly-camera-module.jpg', 'admin', '2021-02-15 02:27:03'),
(11, 'post-11', 'GOOGLE OPENTITAN AND MICROSOFT PLUTON CREATE THE FUTURE OF SECURITY CHIPS', 'OpenTitan is the first open-source project building a transparent, high-quality reference design and integration guidelines for silicon root of trust (RoT) chips (such as TPMs).', 'Before talking about OpenTitan and Microsoft Pluton – two security chips by two tech giants, let’s have an overview of what security chips actually are.Today, the hardware-level security of an operating system is an extremely important matter and is taken very seriously by manufacturers. The core security of an operating system depends on a chip separate from the CPU. This chip is called TPM or Trusted Platform Module. TPM stores various keys and other sensitive information that saves the integrity of the entire system. Security chips are also used in embedded platforms where security is the utmost priority. A good example is IoT based smart home control system. If an attacker gets access to the secure keys of various APIs used for controlling “things” remotely, they can do anything. So, these types of keys are stored in TPM.Silicon Root of Trust (RoT) chips can provide many security benefits by helping to:Ensure that a server or a device boots up with the correct firmware and hasn’t been infected by low-level malware.Provide a cryptographically unique machine identity, so an operator can verify that a server or a device is legitimate.Protect secrets like encryption keys in a tamper-resistant way even for people with physical access (e.g., while a server or a device is being shipped).Provide authoritative, tamper-evident audit records and other runtime security services. Google OpenTitan OpenTitan is the first open-source project building a transparent, high-quality reference design and integration guidelines for silicon root of trust (RoT) chips (such as TPMs). The main goal of OpenTitan is to make the silicon RoT design and implementation more transparent, trustworthy, and secure for enterprises, platform providers, and chip manufacturers. Big companies like Western Digital, Seagate, Nuvoton, etc. are partnering with Google in this project.OpenTitan being open-source, Root of Trust chip designers can embed this in their design with little or no legal complexities. Also, numerous talented developers can contribute to this project and raise the security standard. Open-source silicon can enhance trust and security by design and implementation transparency. problems can be detected early, and bugs can be fixed. This will also provide implementation choices and preserve a set of common interfaces.', 'googleopentitan.jpg', 'admin', '2021-02-15 02:28:09');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contacts`
--
ALTER TABLE `contacts`
  ADD PRIMARY KEY (`sno`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`sno`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contacts`
--
ALTER TABLE `contacts`
  MODIFY `sno` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `sno` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
